CREATE TABLE IF NOT EXISTS ZGLV (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VERSION TEXT NOT NULL,
    DATA TEXT NOT NULL,
    FILENAME TEXT NOT NULL UNIQUE,
    YEAR INTEGER NOT NULL,
    CODE_MO TEXT NOT NULL
);


CREATE INDEX IF NOT EXISTS IX_ZGLV_FILENAME ON ZGLV (FILENAME);


CREATE TABLE IF NOT EXISTS EVENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ZGLV_ID INTEGER NOT NULL,
    DISP TEXT NOT NULL,
    KOL_M INTEGER NOT NULL,
    KOL_W INTEGER NOT NULL,
    FOREIGN KEY (ZGLV_ID) REFERENCES ZGLV(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_EVENT_ZGLV_ID ON EVENT (ZGLV_ID);


CREATE TABLE IF NOT EXISTS PERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    EVENT_ID INTEGER NOT NULL,
    N_ZAP INTEGER NOT NULL,
    ID_PAC TEXT NOT NULL,
    W INTEGER NOT NULL, -- 1 - Мужской, 2 - Женский
    DR TEXT NOT NULL,
    SMO TEXT NOT NULL,
    VPOLIS INTEGER NOT NULL,
    SPOLIS TEXT,
    NPOLIS TEXT NOT NULL,
    QUARTER INTEGER,
    MONTH INTEGER,
    LPU1 TEXT NOT NULL,
    DEPTH TEXT NOT NULL,
    SS_DOC TEXT NOT NULL,
    SS_DOC_D TEXT,
    PRVS_D INTEGER,
    DS_D TEXT,
    PLACE_D INTEGER,
    ID_TFOMS TEXT,
    COMMENT TEXT,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_PERS_EVENT_ID ON PERS (EVENT_ID);
CREATE INDEX IF NOT EXISTS IX_PERS_ID_PAC ON PERS (ID_PAC);
CREATE INDEX IF NOT EXISTS IX_PERS_NPOLIS ON PERS (NPOLIS);
CREATE INDEX IF NOT EXISTS IX_PERS_SS_DOC ON PERS (SS_DOC);

CREATE INDEX IF NOT EXISTS IX_PERS_POLIS ON PERS (SPOLIS, NPOLIS);


CREATE TABLE IF NOT EXISTS CONTACTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PERS_ID INTEGER NOT NULL,
    PHONE_F TEXT,
    PHONE_M TEXT,
    EMAIL TEXT,
    ADDRESS TEXT,
    FOREIGN KEY (PERS_ID) REFERENCES PERS(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IX_CONTACTS_PERS_ID ON CONTACTS (PERS_ID);

CREATE VIEW IF NOT EXISTS V_GENDER_MISMATCH AS
SELECT 
    e.ID AS EventId,
    e.DISP,
    e.KOL_M,
    e.KOL_W,
    COALESCE(SUM(CASE WHEN p.W = 1 THEN 1 ELSE 0 END), 0) AS ActualM,
    COALESCE(SUM(CASE WHEN p.W = 2 THEN 1 ELSE 0 END), 0) AS ActualW
FROM EVENT e
LEFT JOIN PERS p ON e.ID = p.EVENT_ID
GROUP BY e.ID, e.DISP, e.KOL_M, e.KOL_W
HAVING e.KOL_M != ActualM OR e.KOL_W != ActualW;